/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DButton {
        "variant": string;
    }
    interface DHeader {
        "name": string;
    }
    interface DInput {
        "error": string;
        "id": string;
        "label": string;
        "placeholder": string;
        "required": boolean;
        "type": string;
        "value": string;
    }
    interface DLabel {
        "htmlId": string;
        "required": boolean;
    }
    interface DNotification {
        "type": string;
    }
}
export interface DButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDButtonElement;
}
export interface DInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDInputElement;
}
declare global {
    interface HTMLDButtonElement extends Components.DButton, HTMLStencilElement {
    }
    var HTMLDButtonElement: {
        prototype: HTMLDButtonElement;
        new (): HTMLDButtonElement;
    };
    interface HTMLDHeaderElement extends Components.DHeader, HTMLStencilElement {
    }
    var HTMLDHeaderElement: {
        prototype: HTMLDHeaderElement;
        new (): HTMLDHeaderElement;
    };
    interface HTMLDInputElement extends Components.DInput, HTMLStencilElement {
    }
    var HTMLDInputElement: {
        prototype: HTMLDInputElement;
        new (): HTMLDInputElement;
    };
    interface HTMLDLabelElement extends Components.DLabel, HTMLStencilElement {
    }
    var HTMLDLabelElement: {
        prototype: HTMLDLabelElement;
        new (): HTMLDLabelElement;
    };
    interface HTMLDNotificationElement extends Components.DNotification, HTMLStencilElement {
    }
    var HTMLDNotificationElement: {
        prototype: HTMLDNotificationElement;
        new (): HTMLDNotificationElement;
    };
    interface HTMLElementTagNameMap {
        "d-button": HTMLDButtonElement;
        "d-header": HTMLDHeaderElement;
        "d-input": HTMLDInputElement;
        "d-label": HTMLDLabelElement;
        "d-notification": HTMLDNotificationElement;
    }
}
declare namespace LocalJSX {
    interface DButton {
        "onDClick"?: (event: DButtonCustomEvent<any>) => void;
        "variant"?: string;
    }
    interface DHeader {
        "name"?: string;
    }
    interface DInput {
        "error"?: string;
        "id": string;
        "label": string;
        "onDChange"?: (event: DInputCustomEvent<any>) => void;
        "onDInput"?: (event: DInputCustomEvent<any>) => void;
        "placeholder"?: string;
        "required"?: boolean;
        "type"?: string;
        "value"?: string;
    }
    interface DLabel {
        "htmlId": string;
        "required"?: boolean;
    }
    interface DNotification {
        "type"?: string;
    }
    interface IntrinsicElements {
        "d-button": DButton;
        "d-header": DHeader;
        "d-input": DInput;
        "d-label": DLabel;
        "d-notification": DNotification;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "d-button": LocalJSX.DButton & JSXBase.HTMLAttributes<HTMLDButtonElement>;
            "d-header": LocalJSX.DHeader & JSXBase.HTMLAttributes<HTMLDHeaderElement>;
            "d-input": LocalJSX.DInput & JSXBase.HTMLAttributes<HTMLDInputElement>;
            "d-label": LocalJSX.DLabel & JSXBase.HTMLAttributes<HTMLDLabelElement>;
            "d-notification": LocalJSX.DNotification & JSXBase.HTMLAttributes<HTMLDNotificationElement>;
        }
    }
}
