/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DButton {
        "variant": string;
    }
    interface DHeader {
        "name": string;
    }
    interface DNotification {
        "variant": string;
    }
}
export interface DButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDButtonElement;
}
declare global {
    interface HTMLDButtonElement extends Components.DButton, HTMLStencilElement {
    }
    var HTMLDButtonElement: {
        prototype: HTMLDButtonElement;
        new (): HTMLDButtonElement;
    };
    interface HTMLDHeaderElement extends Components.DHeader, HTMLStencilElement {
    }
    var HTMLDHeaderElement: {
        prototype: HTMLDHeaderElement;
        new (): HTMLDHeaderElement;
    };
    interface HTMLDNotificationElement extends Components.DNotification, HTMLStencilElement {
    }
    var HTMLDNotificationElement: {
        prototype: HTMLDNotificationElement;
        new (): HTMLDNotificationElement;
    };
    interface HTMLElementTagNameMap {
        "d-button": HTMLDButtonElement;
        "d-header": HTMLDHeaderElement;
        "d-notification": HTMLDNotificationElement;
    }
}
declare namespace LocalJSX {
    interface DButton {
        "onDClick"?: (event: DButtonCustomEvent<any>) => void;
        "variant"?: string;
    }
    interface DHeader {
        "name"?: string;
    }
    interface DNotification {
        "variant"?: string;
    }
    interface IntrinsicElements {
        "d-button": DButton;
        "d-header": DHeader;
        "d-notification": DNotification;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "d-button": LocalJSX.DButton & JSXBase.HTMLAttributes<HTMLDButtonElement>;
            "d-header": LocalJSX.DHeader & JSXBase.HTMLAttributes<HTMLDHeaderElement>;
            "d-notification": LocalJSX.DNotification & JSXBase.HTMLAttributes<HTMLDNotificationElement>;
        }
    }
}
